# Generated by Django 4.0.5 on 2022-06-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('series_name', models.CharField(max_length=255)),
                ('pub_format', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('publication_date', models.DateField(null=True)),
                ('ISBN_13', models.CharField(blank=True, max_length=30)),
                ('ISBN_10', models.CharField(blank=True, max_length=30)),
                ('ISBN_registered', models.BooleanField()),
                ('ISBN_url', models.URLField(blank=True)),
                ('note', models.TextField()),
            ],
        ),
    ]
