# Generated by Django 4.0.5 on 2022-06-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
    ]
