# Generated by Django 4.0.5 on 2022-06-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groot', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
